version: "3.7"
services:
 web-server:
    build:
      dockerfile: docker/apache/Dockerfile
      context: .
    volumes:
      - "./:/var/www/html/"
    ports:
      - "8080:80"
 mysql-server:
    image: mariadb:10.4
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: '%' 
    volumes:
      - mysql-data:/var/lib/mysql
 my-app:
   env_file:
    - .env
   build:
     dockerfile: docker/app/Dockerfile
     context: . 
volumes:
  mysql-data: